.TH XDRAPE 1 xdrape\-0.2
.SH NAME
xdrape \- X11 window display utility
.SH SYNOPSIS
xdrape [\fIOPTION\fR]...
.SH DESCRIPTION
\fBxdrape\fR
displays an X11 window and prints its window ID to standard output
as a hexadecimal nuber, prefixed with "0x".
.
.SH OPTIONS
.TP
\fB\-m\fR
click to exit
.TP
\fB\-q\fR
press a key to exit
.TP
\fB\-f\fR
run in foreground
.TP
\fB\-o\fR
set override-redirect flag
.TP
\fB\-k\fR
print key presses
.TP
\fB\-K\fR
print key releases
.TP
\fB\-b\fR
print button presses
.TP
\fB\-B\fR
print button releases
.TP
\fB\-s\fR \fINUM\fR
exit after NUM microseconds
.TP
\fB\-c\fR \fICOLOR\fR
set background color
.TP
\fB\-n\fR \fISTR\fR
set WM_NAME
.TP
\fB\-N\fR \fINAME\fR
set resource name
.TP
\fB\-C\fR \fICLASS\fR
set resource class
.TP
\fB\-x\fR \fIPOS\fR
set x position
.TP
\fB\-y\fR \fIPOS\fR
set y position
.TP
\fB\-w\fR \fINUM\fR
set width
.TP
\fB\-h\fR \fINUM\fR
set height
.
.SH AUTHOR
Paul Hoffman <nkuitse@nkuitse.com>
.
.SH LICENSE AND COPYRIGHT
Copyright 2013-2016 Paul M. Hoffman.
.P
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.
.P
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.P
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

